name: flossy-env
channels:
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scipy
  - numba
  - astropy
  - pyqt=5  # For PyQt5
  - pip
  - pip:
      - types-SimpleNamespace  # For SimpleNamespace if needed